sudo: required

services:
- docker

language: java

jdk:
- oraclejdk8

branches:
  only:
  - master
  - development

install: mvn validate
script: mvn clean verify

notifications:
  slack: capbox:P0Wiy75KRAu5XrwM61qqXG3y
