sudo: required

language: java

jdk:
- oraclejdk8

branches:
  only:
  - master
  - development

notifications:
  slack: 'capbox:l2wu5yKg5EAORuhs5gUoH1u0#notifications'
  email: true

script: mvn clean verify
