sudo: required

services:
  - docker

language: java

jdk:
 - oraclejdk8

branches:
  only:
    - master
    - development
    - docker-dojo

install: "mvn clean install -Dmaven.test.skip=true -Dmaven.source.skip=true -Dmaven.javadoc.skip=true"
script: "mvn verify"
